# Generated by Django 5.0.3 on 2024-03-09 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_product_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='camera_resolution',
        ),
        migrations.RemoveField(
            model_name='product',
            name='processor',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ram',
        ),
        migrations.RemoveField(
            model_name='product',
            name='rom',
        ),
        migrations.RemoveField(
            model_name='product',
            name='screen_size',
        ),
        migrations.RemoveField(
            model_name='product',
            name='screen_technology',
        ),
        migrations.RemoveField(
            model_name='product',
            name='video_resolution',
        ),
        migrations.AddField(
            model_name='brand',
            name='brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.category'),
        ),
        migrations.CreateModel(
            name='Harakters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_size', models.CharField(blank=True, max_length=32, null=True, verbose_name='размер экрана')),
                ('screen_technology', models.CharField(blank=True, max_length=50, null=True, verbose_name='технология, используемая на экране (например, OLED)')),
                ('processor', models.CharField(blank=True, max_length=50, null=True, verbose_name='процессор')),
                ('rom', models.IntegerField(blank=True, null=True)),
                ('ram', models.IntegerField(blank=True, null=True, verbose_name='количество ядер')),
                ('camera_resolution', models.CharField(blank=True, max_length=50, null=True)),
                ('video_resolution', models.CharField(blank=True, max_length=50, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.product')),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rom', models.CharField(choices=[('1', '1'), ('2', '2'), ('4', '4'), ('8', '8'), ('16', '16'), ('32', '32'), ('64', '64'), ('128', '128'), ('256', '256'), ('512', '512'), ('1024', '1024'), ('2048', '2048'), ('4096', '4096'), ('8192', '8192')], default='32', max_length=10)),
                ('product', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.product')),
            ],
        ),
    ]
