# Generated by Django 5.0.3 on 2024-03-09 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_caruselphoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='harakters',
            name='rom',
        ),
    ]
