# Generated by Django 5.0.3 on 2024-03-09 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_harakters_rom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='author',
            new_name='user',
        ),
    ]
