# Generated by Django 5.0.3 on 2024-03-10 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_rename_author_reviews_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='user_id',
            new_name='user',
        ),
    ]
